development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: ufc-betting-site_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:74b93202645dfaff3ada8e9dc20fc382@pike.redistogo.com:9120/
  channel_prefix: ufc-betting-site_production
